name: Publish on CurseForge & Modrinth

on: [workflow_dispatch]

env:
  MINECRAFT_VERSION: 1.19.2
  JAVA_VERSION: 17
  VERSION: 1.3.1+1.20.1
  RELEASE_NAME: Botania Configurator 1.3.1 for MC 1.20.1

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Publish (CurseForge/Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: 945531
          curseforge-token: "${{secrets.CURSEFORGE_TOKEN}}"

          modrinth-id: alWa8n3a
          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"

          name: "${{env.RELEASE_NAME}}"
          version: "${{env.VERSION}}"
          version-type: beta
          changelog-file: CHANGELOG.md

          files: |
            build/libs/!(*-@(dev|sources|javadoc)).jar
            build/libs/*-@(dev|sources|javadoc).jar

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"

          dependencies: |
            fabric@0.88.1+1.20.1(required){modrinth:P7dR8mSH}{curseforge:306612}#(ignore:github)
            botania@1.20.1-443-FABRIC(required){modrinth:pfjLUfGv}{curseforge:421839}#(ignore:github)
            midnightlib@1.20.1-443-FABRIC(embedded){modrinth:codAaoxh}{curseforge:488090}#(ignore:github)

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail

